spring.application.name=Guardian-Link
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/guardianlink
spring.datasource.username=root
spring.datasource.password=Qwerty@saima20

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true